"""The ``--packages`` v2 contract (docs/plan/anx-design.md §6.1).

The file is generated by ``anx`` and consumed here; both live in this
repository, so the format is versioned explicitly and an unknown version is an
error rather than a guess.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import cast

from compiler.error import CompilerError

#: Format version this compiler understands. v1 (a flat ``name → sourceRoot``
#: mapping) is deliberately not accepted.
SUPPORTED_FORMAT = 2

#: Package name reserved for the bundled standard library.
STD_PACKAGE = "std"

KINDS = ("bin", "lib", "hybrid")


@dataclass(frozen=True)
class PackageSpec:
    """One package as described by the ``packages`` table."""

    name: str
    source_root: Path
    kind: str
    entry: Path | None  # None for "lib"
    dependencies: tuple[str, ...]  # direct dependencies, by canonical name


@dataclass(frozen=True)
class PackageMap:
    """A parsed ``--packages`` file."""

    root: str | None  # None: no root package, fall back to standalone entry discovery
    packages: Mapping[str, PackageSpec]

    @classmethod
    def parse(cls, path: Path) -> PackageMap:
        """Read and validate the package map at *path*.

        Raises :class:`CompilerError` for anything that is not a complete,
        self-consistent v2 document.
        """
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except OSError as error:
            raise CompilerError(f"could not read --packages file {path}: {error}") from error
        except json.JSONDecodeError as error:
            raise CompilerError(f"could not parse --packages file {path}: {error}") from error

        data = _as_table(raw)
        if data is None:
            raise CompilerError(f"--packages file {path} must contain a JSON object")

        version = data.get("format")
        if version != SUPPORTED_FORMAT:
            raise CompilerError(
                f"--packages file {path} declares format {version!r}; "
                f"this compiler requires format {SUPPORTED_FORMAT}"
            )

        table = _as_table(data.get("packages"))
        if table is None:
            raise CompilerError(f"--packages file {path} must contain a 'packages' object")

        packages: dict[str, PackageSpec] = {}
        for name, value in table.items():
            spec = _as_table(value)
            if spec is None:
                raise CompilerError(f"--packages entry '{name}' must be an object")
            packages[name] = _parse_spec(name, spec)

        if STD_PACKAGE not in packages:
            raise CompilerError(
                f"--packages file {path} must describe the '{STD_PACKAGE}' package"
            )

        root_value = data.get("root")
        if root_value is None:
            root: str | None = None
        elif isinstance(root_value, str) and root_value in packages:
            root = root_value
        else:
            raise CompilerError(
                f"--packages 'root' must name a package declared in the file, got {root_value!r}"
            )

        return cls(root=root, packages=MappingProxyType(packages))

    def source_roots(self) -> dict[str, Path]:
        return {name: spec.source_root for name, spec in self.packages.items()}

    def package_of(self, file: Path) -> str | None:
        """Return the package owning *file*, by longest source-root prefix."""
        resolved = file.resolve()
        best: str | None = None
        best_depth = -1
        for name, spec in self.packages.items():
            if spec.source_root not in resolved.parents:
                continue
            depth = len(spec.source_root.parts)
            if depth > best_depth:
                best = name
                best_depth = depth
        return best

    def visible_from(self, package: str | None) -> frozenset[str]:
        """The packages *package* may import: itself, its direct dependencies, ``std``.

        An unknown importer (a file outside every source root) may reference any
        package in the map; visibility is only meaningful for a known package.
        """
        if package is None:
            return frozenset(self.packages)
        spec = self.packages.get(package)
        if spec is None:
            return frozenset(self.packages)
        return frozenset({package, *spec.dependencies, STD_PACKAGE})

    def entry_paths(self) -> frozenset[Path]:
        """Resolved entry files of every package; none of them may be imported."""
        return frozenset(
            spec.entry for spec in self.packages.values() if spec.entry is not None
        )


def _parse_spec(name: str, spec: dict[str, object]) -> PackageSpec:
    source_root = spec.get("sourceRoot")
    if not isinstance(source_root, str) or source_root == "":
        raise CompilerError(f"--packages entry '{name}' needs a non-empty 'sourceRoot'")

    kind = spec.get("kind", "bin")
    if not isinstance(kind, str) or kind not in KINDS:
        raise CompilerError(f"--packages entry '{name}' has invalid kind {kind!r}")

    entry_value = spec.get("entry")
    if entry_value is None:
        entry: Path | None = None
    elif isinstance(entry_value, str) and entry_value != "":
        entry = Path(entry_value).resolve()
    else:
        raise CompilerError(f"--packages entry '{name}' has an invalid 'entry'")

    dependencies_value = spec.get("dependencies", [])
    if not isinstance(dependencies_value, list):
        raise CompilerError(f"--packages entry '{name}' has a non-array 'dependencies'")
    dependencies: list[str] = []
    for dependency in cast("list[object]", dependencies_value):
        if not isinstance(dependency, str):
            raise CompilerError(f"--packages entry '{name}' has a non-string dependency")
        dependencies.append(dependency)

    return PackageSpec(
        name=name,
        source_root=Path(source_root).resolve(),
        kind=kind,
        entry=entry,
        dependencies=tuple(dependencies),
    )


def _as_table(value: object) -> dict[str, object] | None:
    """Return *value* as a string-keyed table, or ``None`` when it is not one."""
    if not isinstance(value, dict):
        return None
    table: dict[str, object] = {}
    for key, item in cast("dict[object, object]", value).items():
        if not isinstance(key, str):
            return None
        table[key] = item
    return table
